# tutorial installazione nginx https://www.cyberciti.biz/faq/how-to-install-nginx-web-server-on-alpine-linux/

# installare debian come immagine 
FROM alpine:latest

# settare un amministratore
MAINTAINER donny way <mionome@outlook.com>

# installare prima la tua repo <apk update> dopo installare nginx < apk add nginx>
RUN	apk update && apk add nginx

CMD ["echo", "Sto crendo l'immagine di nginx "]
